#! /bin/bash
set -e

#Utiliser pour créer un fichier de settings en fonction des variables d'environnement (envoyé par Docker)

HTTPS_PORT_SUFFIX=""
if [ "${HTTPS_PORT}" != "443" ]; then
  HTTPS_PORT_SUFFIX=":${HTTPS_PORT}"
fi

cat <<EOF
<?php

define("SITE_BASE","https://${APP_HOST}${HTTPS_PORT_SUFFIX}");
define("WEBSEC_BASE","https://${MAILSEC_HOST}${HTTPS_PORT_SUFFIX}");

define("TIMEZONE", "${TZ:-Europe/Paris}");
define("BD_DSN","mysql:dbname=${DATABASE_NAME:-pastell};host=${DATABASE_HOST:-db};port=${DATABASE_PORT:-3306};charset=utf8mb4");
define("BD_DBNAME","${DATABASE_NAME:-pastell}");
define("BD_USER","${DATABASE_USER:-pastell}");
define("BD_PASS","${DATABASE_PASSWORD}");

define("BD_DSN_TEST","mysql:dbname=${DATABASE_NAME_TEST:-pastell_test};host=${DATABASE_HOST_TEST:-db_test};port=${DATABASE_PORT_TEST:-3306};charset=utf8mb4");
define("BD_DBNAME_TEST","${DATABASE_NAME_TEST:-pastell_test}");
define("BD_USER_TEST","${DATABASE_USER_TEST:-pastell}");
define("BD_PASS_TEST","${DATABASE_PASSWORD_TEST}");

define("WORKSPACE_PATH" , "/data/workspace");

define("PLATEFORME_MAIL","${PLATEFORME_MAIL}");

define("REDIS_SERVER","${REDIS_SERVER}");
define("REDIS_PORT",${REDIS_PORT:-6379});

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

define("LOG_FILE","/data/log/pastell.log");
define("LOG_LEVEL", Monolog\Logger::${LOG_LEVEL:-INFO});

define("SENTRY_DSN", "${SENTRY_DSN}");
define("SENTRY_ENVIRONMENT", "${SENTRY_ENVIRONMENT:-dev}");

define("PES_VIEWER_URL", "${PES_VIEWER_URL:-http://pes-viewer:8888}");

define("MAILER_DSN", "${MAILER_DSN:-null://null}");

define("ADMIN_EMAIL", "${ADMIN_EMAIL:-test@libriciel.invalid}");

define("PASTELL_ADMIN_EMAIL", "${PASTELL_ADMIN_EMAIL:-test@libriciel.invalid}");
define("PASTELL_ADMIN_LOGIN", "${PASTELL_ADMIN_LOGIN:-admin}");

\$packs = [];
if (${PACK_CHORUS_PRO:-false}) {
  \$packs["pack_chorus_pro"]=true;
}
if (${PACK_MARCHE:-false}) {
  \$packs["pack_marche"]=true;
}
if (${PACK_URBANISME:-false}) {
  \$packs["pack_urbanisme"]=true;
}
if (${PACK_RH:-false}) {
  \$packs["pack_rh"]=true;
}
if (${PACK_TEST:-false}) {
  \$packs["suppl_test"]=true;
}

if (${PACK_RECUP_PARAPHEUR_CORBEILLE_CONNECTOR:-false}) {
  \$packs["suppl_recup_parapheur_corbeille_connector"]=true;
}

if (${PACK_RECUP_FIN_PARAPHEUR:-false}) {
  \$packs["suppl_recup_fin_parapheur"]=true;
}

if (${PACK_RECUP_ACTES_S2LOW:-false}) {
  \$packs["suppl_recup_actes_s2low"] = true;
}

if (${PACK_RECUP_PES_S2LOW:-false}) {
  \$packs["suppl_recup_pes_s2low"] = true;
}

if (${PACK_ACTES_TDT_VERSANT_SAE:-false}) {
  \$packs["suppl_actes_tdt_versant_sae"] = true;
}

if (${PACK_HELIOS_TDT_VERSANT_SAE:-false}) {
  \$packs["suppl_helios_tdt_versant_sae"] = true;
}

if (${PACK_FAST_CONNECTORS:-false}) {
  \$packs["module_connecteur_fast"] = true;
}

if (${PACK_VITAM_CONNECTORS:-false}) {
  \$packs["module_connecteur_vitam"] = true;
}

define("LIST_PACK", \$packs);

define("NB_WORKERS", "${NB_WORKERS:-5}");
define("JOURNAL_MAX_AGE_IN_DAYS", "${JOURNAL_MAX_AGE_IN_DAYS:-60}");
define("UNLOK_JOB_ERROR_AT_STARTUP", "${UNLOK_JOB_ERROR_AT_STARTUP:-false}");
define("NB_JOB_PAR_VERROU", "${NB_JOB_PAR_VERROU:-1}");
define("HTTP_PROXY_URL", "${HTTP_PROXY_URL:-}");
define("NO_PROXY", "${NO_PROXY:-localhost,127.0.0.1,::1,seda-generator,pes-viewer}");
define("PASSWORD_MIN_ENTROPY", "${PASSWORD_MIN_ENTROPY:-80}");

define("USE_UUID_FOR_DOCUMENT", ${USE_UUID_FOR_DOCUMENT:-false});

define("S3_URL", "${S3_URL:-http://minio:9000/}");
define("S3_KEY", "${S3_KEY:-minioadmin}");
define("S3_SECRET", "${S3_SECRET:-minioadmin}");
define("S3_BUCKET_JOURNAL", "${S3_BUCKET_JOURNAL:-journal-preuves}");
define("USE_EXTERNAL_STORAGE_FOR_JOURNAL_PROOF", ${USE_EXTERNAL_STORAGE_FOR_JOURNAL_PROOF:-false});

define('RATE_LIMITER_VARIABLE', '${RATE_LIMITER_VARIABLE:-REMOTE_ADDR}');
define('ARCHIVE_CREATION_TIMEOUT', '${ARCHIVE_CREATION_TIMEOUT:-1200}');

define('DISPLAY_SECURITY_BANNER', ${DISPLAY_SECURITY_BANNER:-true});

EOF

env | grep '^TOGGLE_' | sed "s/^TOGGLE_\([^=]*\)=\(.*\)/\$feature_toggle[Pastell\\\Service\\\FeatureToggle\\\\\1::class] = \2;/g"
