Protocols h2 http/1.1

# TLS Protocols
SSLProtocol -all +TLSv1.3 +TLSv1.2

# Cipher Suites (TLSv1.2 only, TLSv1.3 uses its own internal suite)
SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
SSLHonorCipherOrder on
SSLSessionTickets off

# OCSP Stapling
SSLUseStapling On
SSLStaplingCache "shmcb:logs/ssl_stapling(32768)"

# Reducing MIME type security risks
Header set X-Content-Type-Options "nosniff"
# HTTP Strict Transport Security (HSTS)
Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"
# Server software information
Header always unset X-Powered-By
ServerTokens Prod
ServerSignature Off

Header set Content-Security-Policy "frame-ancestors 'self';"
Header set Referrer-Policy: same-origin
Header set Permissions-Policy "accelerometer=(), geolocation=self, fullscreen=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), display-capture=self"