name: pastell

services:
  app:
    image: 'registry.libriciel.fr/public/plateforme/pastell-app:canary'
    init: true
    restart: unless-stopped
    read_only: true
    stop_grace_period: 60s
    stop_signal: SIGTERM
    depends_on:
      - db
      - redis
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    user: "${UID:-10001}:${GID:-10001}"
    environment:
      APP_HOST: ${APP_HOST:?}
      MAILSEC_HOST: ${MAILSEC_HOST:?}
      HTTPS_PORT: ${HTTPS_PORT:-443}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-1000M}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE:-200M}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:-200M}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-600}
      REDIS_SERVER: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      PLATEFORME_MAIL: ${PLATEFORME_MAIL:-noreply@libriciel.invalid}
      PASTELL_ADMIN_LOGIN: ${PASTELL_ADMIN_LOGIN:-admin}
      PASTELL_ADMIN_EMAIL: ${PASTELL_ADMIN_EMAIL:-test@libriciel.invalid}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_NAME: ${DATABASE_NAME:-pastell}
      DATABASE_USER: ${DATABASE_USER:-pastell}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?}
      SENTRY_DSN: ${SENTRY_DSN:-}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT:-dev}
      MAILER_DSN: ${MAILER_DSN:-null://null}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-test@libriciel.invalid}
      PACK_CHORUS_PRO: ${PACK_CHORUS_PRO:-false}
      PACK_MARCHE: ${PACK_MARCHE:-false}
      PACK_MARCHE_LS_DOSSIER_MARCHE: ${PACK_MARCHE_LS_DOSSIER_MARCHE:-false}
      PACK_URBANISME: ${PACK_URBANISME:-false}
      PACK_RH: ${PACK_RH:-false}
      PACK_TEST: ${PACK_TEST:-false}
      PACK_LIBERSIGN: ${PACK_LIBERSIGN:-false}
      PACK_RECUP_PARAPHEUR_CORBEILLE_CONNECTOR: ${PACK_RECUP_PARAPHEUR_CORBEILLE_CONNECTOR:-false}
      PACK_RECUP_FIN_PARAPHEUR: ${PACK_RECUP_FIN_PARAPHEUR:-false}
      PACK_RECUP_ACTES_S2LOW: ${PACK_RECUP_ACTES_S2LOW:-false}
      PACK_RECUP_PES_S2LOW: ${PACK_RECUP_PES_S2LOW:-false}
      PACK_ACTES_TDT_VERSANT_SAE: ${PACK_ACTES_TDT_VERSANT_SAE:-false}
      PACK_HELIOS_TDT_VERSANT_SAE: ${PACK_HELIOS_TDT_VERSANT_SAE:-false}
      PACK_FAST_CONNECTORS: ${PACK_FAST_CONNECTORS:-false}
      PACK_VITAM_CONNECTORS: ${PACK_VITAM_CONNECTORS:-false}
      TZ: ${TZ:-Europe/Paris}
      LOCALE: ${LOCALE:-fr_FR.UTF-8}
      NB_WORKERS: ${NB_WORKERS:-5}
      JOURNAL_MAX_AGE_IN_DAYS: ${JOURNAL_MAX_AGE_IN_DAYS:-60}
      UNLOK_JOB_ERROR_AT_STARTUP: ${UNLOK_JOB_ERROR_AT_STARTUP:-false}
      NB_JOB_PAR_VERROU: ${NB_JOB_PAR_VERROU:-1}
      HTTP_PROXY_URL: ${HTTP_PROXY_URL:-}
      NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1,::1,seda-generator,pes-viewer}
      TOGGLE_CDGFeature: ${TOGGLE_CDGFeature:-false}
      USE_UUID_FOR_DOCUMENT: ${USE_UUID_FOR_DOCUMENT:-false}
      PASSWORD_MIN_ENTROPY: ${PASSWORD_MIN_ENTROPY:-80}
      RATE_LIMITER_VARIABLE: ${RATE_LIMITER_VARIABLE:-REMOTE_ADDR}
      DISPLAY_SECURITY_BANNER: ${DISPLAY_SECURITY_BANNER:-true}
    tmpfs:
      - /data/config:mode=770,uid=${UID:-10001},gid=${GID:-10001},rw,noexec,nosuid,nodev
      - /data/run:mode=770,uid=${UID:-10001},gid=${GID:-10001},rw,noexec,nosuid,nodev
      - /data/lock:mode=770,uid=${UID:-10001},gid=${GID:-10001},rw,noexec,nosuid,nodev
      - /data/html_purifier:mode=770,uid=${UID:-10001},gid=${GID:-10001},rw,noexec,nosuid,nodev
      - /var/run:mode=770,uid=${UID:-10001},gid=${GID:-10001},rw,noexec,nosuid,nodev
      - /app/var:mode=770,uid=${UID:-10001},gid=${GID:-10001},rw,noexec,nosuid,nodev
    volumes:
      - ${PASTELL_EXTENSION_PATH:-../../}:/data/extensions/:ro,noexec,nosuid,nodev
      - ${WORKSPACE_VOLUME:-app_workspace}:/data/workspace/:rw,nosuid,nodev
      - ${PASTELL_SESSION:-app_session}:/data/session/:rw,noexec,nosuid,nodev
      - ${APP_LOGS_PATH:-app_logs_datadir}:/data/log/:rw,noexec,nosuid,nodev
      - ${TMP_PATH:-tmp_datadir}:/tmp/:rw,noexec,nosuid,nodev
      - ${UPLOAD_CHUNK_PATH:-upload_chunk_datadir}:/data/upload_chunk/:rw,noexec,nosuid,nodev
      - ${CACERTS_PATH:-cacerts}:/etc/ssl/certs/:ro,noexec,nosuid,nodev
      - ${LIBRICIEL_FEEDBACK_VOLUME:-libriciel-feedback}:/data/libriciel_feedback/:ro,noexec,nosuid,nodev

  web:
    image: 'registry.libriciel.fr/public/plateforme/pastell-web:canary'
    restart: unless-stopped
    read_only: true
    depends_on:
      - app
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    user: "www-data:www-data"
    environment:
      APP_HOST: ${APP_HOST:?}
      MAILSEC_HOST: ${MAILSEC_HOST:?}
      ACME_APP_ENABLED: ${ACME_APP_ENABLED:-false}
      ACME_APP_SERVER: ${ACME_APP_SERVER:-}
      ACME_APP_EMAIL: ${ACME_APP_EMAIL:-}
      ACME_APP_DOMAIN: ${ACME_APP_DOMAIN:-}
      ACME_APP_ADDITIONAL_DOMAINS: ${ACME_APP_ADDITIONAL_DOMAINS:-}
      ACME_APP_RENEW_BEFORE_DAYS: ${ACME_APP_RENEW_BEFORE_DAYS:-30}
      ACME_APP_EAB_KID: ${ACME_APP_EAB_KID:-}
      ACME_APP_EAB_HMAC_KEY: ${ACME_APP_EAB_HMAC_KEY:-}
      ACME_APP_DEST: ${ACME_APP_DEST:-/data/certificates/app}
      ACME_MAILSEC_ENABLED: ${ACME_MAILSEC_ENABLED:-false}
      ACME_MAILSEC_SERVER: ${ACME_MAILSEC_SERVER:-}
      ACME_MAILSEC_EMAIL: ${ACME_MAILSEC_EMAIL:-}
      ACME_MAILSEC_DOMAIN: ${ACME_MAILSEC_DOMAIN:-}
      ACME_MAILSEC_RENEW_BEFORE_DAYS: ${ACME_MAILSEC_RENEW_BEFORE_DAYS:-30}
      ACME_MAILSEC_EAB_KID: ${ACME_MAILSEC_EAB_KID:-}
      ACME_MAILSEC_EAB_HMAC_KEY: ${ACME_MAILSEC_EAB_HMAC_KEY:-}
      ACME_MAILSEC_DEST: ${ACME_MAILSEC_DEST:-/data/certificates/mailsec}
      HTTP_PORT: ${HTTP_PORT:-80}
      HTTPS_PORT: ${HTTPS_PORT:-443}
    tmpfs:
      - /tmp:mode=770,uid=82,gid=82,rw,noexec,nosuid,nodev
      - /acme-challenge/.well-known/acme-challenge:mode=770,uid=82,gid=82,size=10M,rw,noexec,nosuid,nodev
      - /data/run:mode=770,uid=82,gid=82,size=1M,rw,noexec,nosuid,nodev
    volumes:
      - ${WEB_LOGS_PATH:-web_logs_datadir}:/data/log:rw,noexec,nosuid,nodev
      - ${WEB_CERTIFICATES_PATH:-web_certificates_datadir}:/data/certificates:rw,noexec,nosuid,nodev
      - ${ACME_DATADIR:-acme_datadir}:/etc/letsencrypt:rw,noexec,nosuid,nodev
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"

  db:
    image: 'hubdocker.libriciel.fr/mariadb:11.4.13-noble@sha256:611a2fcc5fa7c6ceb8644c6f74b25ede004ff6c3a6b38c8f8c23d3bbf6c26430'
    restart: unless-stopped
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:?}
      MYSQL_USER: ${DATABASE_USER:-pastell}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:?}
      MYSQL_DATABASE: ${DATABASE_NAME:-pastell}
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev
      - /run/mysqld:rw,noexec,nosuid,nodev
    volumes:
      - ${DATABASE_DATADIR:-database_datadir}:/var/lib/mysql/:rw,noexec,nosuid,nodev

  redis:
    image: 'hubdocker.libriciel.fr/redis:8.10.1-alpine3.23@sha256:becdda6c7f4b3fb42e42fd7f120bbf5c54c4caaaf16f26da24e4563d2c1f0576'
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:mode=750,rw,noexec,nosuid,nodev

  seda-generator:
    image: 'registry.libriciel.fr/public/plateforme/seda-generator:1.2.0@sha256:b2e2b8ddf03cf9c1be2f8ff7d86f37d610d6d766bc46a138046784256b446953'
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    user: "app:app"
    environment:
      TZ: ${TZ:-Europe/Paris}
    tmpfs:
      - /tmp:mode=770,uid=10001,gid=10001,rw,noexec,nosuid,nodev
      - /app/var:mode=770,uid=10001,gid=10001,rw,noexec,nosuid,nodev
      - /data/run:mode=770,uid=10001,gid=10001,size=1M,rw,noexec,nosuid,nodev
      - /var/lib/nginx/tmp:mode=770,uid=10001,gid=10001,rw,noexec,nosuid,nodev

  flow:
    image: 'registry.libriciel.fr/public/libriciel/outils-documentaires/flow:1.7.0@sha256:731db41b3889113e65898d3f8afeed664bf8da92688c6afbbfb47dd956246995'
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:mode=0700,uid=100001,gid=100001,rw,noexec,nosuid,nodev,size=1g

  cloudooo:
    image: 'registry.libriciel.fr/public/actes/cloudooo:25.2.7-rc.3@sha256:524987e6d9c389ed4cac08c5169774a0ade6dda95153a3f1e9ffd601782b03c5'
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  pes-viewer:
    image: 'registry.libriciel.fr/public/signature/pes-viewer:4.0.2@sha256:22ea18abcd74bb56a266d58fadedc2b6d906699cf88991e7dadfc66056e12a3a'
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 1536M
    volumes:
      - ${PES_PJ_PATH:-/data/pastell/pesPJ}:/pesPJ/

  cacerts:
    image: 'registry.libriciel.fr/public/libriciel/ls-docker-cacerts:0.4.0@sha256:209976b9b07ce001403111203f7824bfc57068f033a9c498416a363709690a2d'
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${CACERTS_PATH:-cacerts}:/etc/ssl/certs/:rw,noexec,nosuid,nodev
      - ${LOCAL_CACERTS_PATH:-local_cacerts}:/usr/local/share/ca-certificates:rw,noexec,nosuid,nodev

  libriciel-feedback:
    image: 'registry.libriciel.fr/public/libriciel/deploiement/libriciel-feedback:2.0.7@sha256:27f9b1343e557fdf174201d8a29603637041b61a397c580f7db16aa9ca12f22b'
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    user: "10001:10001"
    tmpfs:
      - /home/feedback:mode=700,uid=10001,gid=10001
    volumes:
      - ${LIBRICIEL_FEEDBACK_VOLUME:-libriciel-feedback}:/var/run/feedback/:rw,noexec,nosuid,nodev
    environment:
      ALLO_TOKEN: ${ALLO_TOKEN:-}
      VERSION: canary

  libriciel-stack-update:
    image: 'registry.libriciel.fr/public/libriciel/deploiement/libriciel-stack-update:1.1.3@sha256:65b093c92172cd971ba294707851202b5ab021b13bb5d729bf63e530e3304e59'
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/pastell:/opt/pastell:rw
      - ${LIBRICIEL_FEEDBACK_VOLUME:-libriciel-feedback}:/var/run/feedback/:ro
      - ${LIBRICIEL_STACK_UPDATE_VOLUME:-/data/pastell/libriciel-stack-update}/config:/var/run/stack-update/:ro
      - ${LIBRICIEL_STACK_UPDATE_VOLUME:-/data/pastell/libriciel-stack-update}/result:/var/run/stack-update-result/:rw
      - ${LIBRICIEL_STACK_UPDATE_VOLUME:-/data/pastell/libriciel-stack-update}/log:/var/log/libriciel-stack-update/:rw
    environment:
      CURRENT_VERSION: "PA canary"
      TZ: ${TZ:-Europe/Paris}
    networks:
      - stack-update-network

  libriciel-postfix:
    image: 'registry.libriciel.fr/public/systeme/libriciel-postfix:1.0.1@sha256:06e0feeb32c390f1c970ef86710ec4eac6c6d232ccfcaa3a5b410c1e5377ecda'
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - CHOWN
      - FOWNER
    environment:
      TENANT_ID: ${GAPI_TENANT_ID:-}
      CLIENT_ID: ${GAPI_CLIENT_ID:-}
      CLIENT_SECRET: ${GAPI_CLIENT_SECRET:-}
      MAILBOX: ${GAPI_MAILBOX:-}
      MAIL_HTTP_PROXY: ${MAIL_HTTP_PROXY:-}
      MAIL_HTTPS_PROXY: ${MAIL_HTTPS_PROXY:-}
    tmpfs:
      - /var/cache/graphapi:uid=1000,gid=1000,mode=0700,noexec,nosuid,nodev
      - /etc/postfix:uid=0,gid=0,mode=0755,noexec,nosuid,nodev
      - /var/lib/postfix:uid=100,gid=0,mode=0755,nosuid,nodev
    volumes:
      - ${EMAIL_PATH:-/data/pastell/libriciel-postfix}:/config:ro,noexec,nosuid,nodev
      - ${EMAIL_PATH:-/data/pastell/libriciel-postfix}/cache:/var/spool/postfix:noexec,nosuid,nodev*

volumes:
  web_logs_datadir:
  web_certificates_datadir:
  acme_datadir:
  database_datadir:
  app_workspace:
  app_session:
  app_logs_datadir:
  tmp_datadir:
  upload_chunk_datadir:
  cacerts:
  local_cacerts:
  libriciel-feedback:

networks:
  stack-update-network:
    driver: bridge