[supervisorctl]
serverurl=unix:///data/run/supervisor.sock ; use a unix:// URL  for a unix socket

[unix_http_server]
file=/data/run/supervisor.sock  ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
logfile=/data/log/supervisord.log
childlogdir = /data/log/
pidfile=/data/run/supervisord.pid

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize
autostart=true
autorestart=true
stdout_logfile=/data/log/fpm-stdout.log
stderr_logfile=/data/log/fpm-stderr.log
pidfile=/data/run/fpm.pid

[program:pastell-daemon]
command=/app/bin/console app:daemon:start
autorestart=true
stdout_logfile=/data/log/pastell-daemon-stdout.log
stderr_logfile=/data/log/pastell-daemon-stderr.log
stopwaitsecs=60
stopsignal=TERM

[program:supercronic]
command=/usr/bin/supercronic /data/config/crontab
autostart=true
autorestart=true
stdout_logfile=/data/log/supercronic-stdout.log
stderr_logfile=/data/log/supercronic-stderr.log