services:
  keycloak:
    image: keycloak/keycloak:26.5@sha256:45ae20191531eb608ddb0b775d012b40d3e4f942697f3214694887dd7c108d13
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_USER:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD:-admin}
    volumes:
      - ./keycloak_pastell.json:/opt/keycloak/data/import/keycloak.json
    command:
      - 'start-dev'
      - '--import-realm'
    ports:
      - "9090:8080"

