services:
  keycloak:
    image: keycloak/keycloak:26.7@sha256:f1f1f01e472c8a78df40d8f2a49a925274eda4d3d80d5f6edbb5c880ee3c01c6
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_USER:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD:-admin}
    volumes:
      - ./keycloak_pastell.json:/opt/keycloak/data/import/keycloak.json
    command:
      - 'start-dev'
      - '--import-realm'
    ports:
      - "9090:8080"

