services:
  keycloak:
    image: hubdocker.libriciel.fr/keycloak/keycloak:26.7@sha256:82a77884f3af238beab1e7afd63b5f530e1b5c0590bd7aa60b40a40463e29b2c
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_USER:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD:-admin}
    volumes:
      - ./keycloak_pastell.json:/opt/keycloak/data/import/keycloak.json
    command:
      - 'start-dev'
      - '--import-realm'
    ports:
      - "9090:8080"

